"""empty message

Revision ID: 12e9e3bf01d8
Revises: 
Create Date: 2026-01-21 15:05:38.945477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e9e3bf01d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('left_text', sa.String(length=100), nullable=False),
    sa.Column('right_text', sa.String(length=100), nullable=False),
    sa.Column('left_score', sa.Integer(), nullable=False),
    sa.Column('right_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
